### ISSUE TITLE
Clarify when user can(not) approve

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PageApprovals#109]
When on a page, it is not clear whether I am allowed to approve a page:
* the indicator/button looks the same
* the mouse hover looks the same and suggests it is clickable

The indicator/button can be perceived as "broken" if it looks exactly the same.

[clarify.webm](https://github.com/user-attachments/assets/6b288abb-c00e-42d3-8d03-3b63bf2acb6a)

AC:
* Remove at least the hover similarities (cursor)
* Ideally make the indicator visually different for approvers and non-approvers

**Comment by waximabbax** [comment]
I remember suggesting an arrow on the right side of the approved badge button only for the approver to make it look like it's a dropdown with options.  

![dropdown](https://github.com/user-attachments/assets/ad95d95e-2522-4632-87b9-73ff30078259)

**Comment by JeroenDeDauw** [comment]
@waximabbax sound reasonable to me, but don't forget this AC:

* Remove at least the hover similarities (cursor)

**Comment by JeroenDeDauw** [comment]
Slite does not have a visual icon to indicate your can click the approval thing. I'm getting the impression you can always change the approval status. Or maybe I'm wrong and normal users cannot. Difficult to test quickly. But for sure they do not have an icon.

https://github.com/user-attachments/assets/cf5ed9bf-bb6c-4f80-8717-7c58d65247dd

**Comment by malberts** [comment]
That popup contains both actions and info. So theoretically that popup could always be triggered, even if I did not have permission to do any of those actions.
