### ISSUE TITLE
UX improvements for adding multiple categories

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#114]
When adding a category, the focus should we set on the New Category input, so the next category can be typed without first clicking the field again.

Current undesired behavior:

https://github.com/user-attachments/assets/4c8ebc26-ea8f-49f7-9499-ae1e44d72773

**Comment by waximabbax** [comment]
Closed by:

https://github.com/ProfessionalWiki/PageApprovals/pull/116
