### ISSUE TITLE
Create task list UI

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#23]
New special page that lists [pending approvals for the current user](https://github.com/ProfessionalWiki/PageApprovals/issues/24). 

Part of 
* https://github.com/ProfessionalWiki/PageApprovals/issues/7

Builds upon
* https://github.com/ProfessionalWiki/PageApprovals/issues/24

**Comment by malberts** [comment]
Initial implementation is done.
