### ISSUE TITLE
Add approver administration right

### ISSUE THREAD

**Issue by waximabbax** [ProfessionalWiki/PageApprovals#31]
AC
* New right exists
* Management of approver config can only be done by users with said right
* Administrators (sysop) should have this right by default

**Comment by waximabbax** [comment]
Not needed anymore.

**Comment by JeroenDeDauw** [comment]
Why not?

**Comment by JeroenDeDauw** [comment]
I suspect that you are confusing this with the not-needed right for approvals. This task is about a right for being able to create approvers and modify which categories they are approver for.

**Comment by waximabbax** [comment]
> I suspect that you are confusing this with the not-needed right for approvals. This task is about a right for being able to create approvers and modify which categories they are approver for.

Oh! But you commented this exactly where I was checking if Admin can access this Page and manage approvers and also where I mentioned this ticket. 

Comment: https://github.com/ProfessionalWiki/PageApprovals/pull/17/files#r1659083902


 and you said its only 2 lines of code which you can commit on top of this branch.
 
 
  **But anyway, I guess I misunderstood, let's keep it open then.**

**Comment by JeroenDeDauw** [comment]
https://github.com/ProfessionalWiki/PageApprovals/pull/50/commits/41cfe6880340b1f71c31acd2f9b7ecdbf8a7b6ad
