### ISSUE TITLE
Show approval UI conditionally  

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#34]
Follow up to
* https://github.com/ProfessionalWiki/PageApprovals/issues/2

AC:
* UI only shows on pages that have at least one category with at least one associated approver

---

Implementation thoughts: our current DB schema does not allow efficiently finding if a category has an associated approver, since we store a JSON array with categories per approver.

We probably need to refactor that to something more (de)normalized (I always forget which one is which): having an `approver_categories` table with one row per category per approver. So 2 columns `ac_user_id`, `ac_category_name`. Maybe that should fully replace the existing table with the JSON array.

**Comment by waximabbax** [comment]
I am not sure how many categories could a single page have in Mediawiki.

Time complexity of `array_intersect` in going to be `O(n*m)` at max. When we fetch all the categories from `approver_config` and make sure that they are unique, e.g.:


```
 public function getCategoriesWithApprovers(): array {
        $result = $this->database->select(
            'approver_config',
            ['ac_categories'],
            [],
            __METHOD__
        );

        $allCategories = [];
        foreach ($result as $row) {
            $categories = $this->deserializeCategories($row->ac_categories);
            $allCategories = array_merge($allCategories, $categories);
        }

        return array_unique(array_filter($allCategories));
    }
    
 ```

I think it should take less than a second even with 2000X2000 on a basic machine.
MySQL might consume similar resources even if we alter the table or create a new table.

**Comment by JeroenDeDauw** [comment]
That `array_filter` looks not needed. `array_map` takes varargs, so you could do something like 

`array_unique(array_merge(...array_map($this->deserializeCategories(...), $result)))`

Note that both `...` are actual PHP syntax

**Comment by JeroenDeDauw** [comment]
"less than a second" is not good enough for something we do on every page load. We can't slow down the page load even by 0.1 seconds.

Caching can be something to consider. Unclear to me if it is warranted. 

Pages could have several dozen categories, though those are already exceptional cases. Typically you have less than 5, and most often either 0 or 1. The array_intersect should not be an issue. Getting the categories from the DB is what we need to pay attention to.

We could cache that list of categories. If we have a good nonvolatile place to store it, we could update this value every time the approver config is changed. That save taking 0.1 seconds longer is totally fine.

... At some point we will be jumping though more hoops than the straightforward and more-future proof refactor.

**Comment by waximabbax** [comment]
> That `array_filter` looks not needed. `array_map` takes varargs, so you could do something like
> 
> `array_unique(array_merge(...array_map($this->deserializeCategories(...), $result)))`
> 
> Note that both `...` are actual PHP syntax

I pasted this from Claude to convey my idea, it likely has some errors or not needed things. I'll definitely format it and checking it before creating PR.

**Comment by waximabbax** [comment]
> Pages could have several dozen categories, though those are already exceptional cases. Typically you have less than 5, 
 > and most often either 0 or 1. The array_intersect should not be an issue. Getting the categories from the DB is what we ?
> need to pay attention to.
 
 We will have only one DB query running when the page loads regardless of the no of categories with the approach I am suggesting.
 
 Getting the data from DB will likely come at the same speed whether we create new table or use existing table.

**Comment by waximabbax** [comment]
I am unsure how creating a new table for categories would make the page load faster than what I suggested. 

Here is a WIP PR:

https://github.com/ProfessionalWiki/PageApprovals/issues/34

**Comment by JeroenDeDauw** [comment]
Performance indeed should not be an issue, as long as the amount of reviewers does not become large, which I don't expect to happen.

**Comment by waximabbax** [comment]
Closed by:

https://github.com/ProfessionalWiki/PageApprovals/pull/82
