### ISSUE TITLE
Make approval UI talk to REST endpoints

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#35]
Follow up to
* https://github.com/ProfessionalWiki/PageApprovals/issues/2

**Comment by JeroenDeDauw** [comment]
@waximabbax you finished this, right?

**Comment by malberts** [comment]
This will be affected by #37. I think it will make sense to update the JS as part of that task.

**Comment by waximabbax** [comment]
> @waximabbax you finished this, right?

Yes.
