### ISSUE TITLE
Implement UI and API for Approver Category Management

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#4]
AC:
* [x] New special page, only accessible by admins
* [x] Can add and remove categories for existing approvers
* [x] Can remove approvers (drop their record from the appover_config table)
* [x] Can add new approvers and assign categories to them

Potentially  as follow-up:
* [x] Only people with new approval administration right can access the page https://github.com/ProfessionalWiki/PageApprovals/issues/31

---

Ideas so far: Table with user and categorie**s** columns. Ability to add new rows

**Comment by waximabbax** [comment]
Should we cover the BE too in the scope of this? Its probably better to do it separately. If we are not gonna add any HTML separately then we only need to create ENDPOINTs for adding a category to the approver and deleting a category from the approver. The way we are setting category in this open [PR](https://github.com/ProfessionalWiki/PageApprovals/pull/16/files#diff-15b1dfdffb2b773e3afd5fee54318c7f3c5b011ce5d3b74baa48ee688f1109b8R38), perhaps we can do it through just one endpoint.

**Comment by malberts** [comment]
Initial implementation is done.
