### ISSUE TITLE
Make approval UI nice

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#45]
Follow up to 
* https://github.com/ProfessionalWiki/PageApprovals/issues/2

NotNice.png:
![image](https://github.com/ProfessionalWiki/PageApprovals/assets/146040/d0e55408-b148-4192-a675-55bc5de95963)

Related
* https://github.com/ProfessionalWiki/PageApprovals/issues/46

**Comment by JeroenDeDauw** [comment]
Perhaps we can do something similar to https://chat.professional.wiki/pro-wiki/channels/bayer-tech/5ajgr4tfhby35mzihaqnd9mkar? 

Perhaps we can move it to the right of the title
![image](https://github.com/ProfessionalWiki/PageApprovals/assets/146040/a6dd72b6-9041-47ed-a778-aa9cf144e11b)

Or failing that, at least make the UI take up only one line, by putting the approval button inside of the banner, or perhaps next to it. The button should also not be the most prominent element on the page, as that'd be very distracting during normal wiki usage by people who are approvers.

**Comment by JeroenDeDauw** [comment]
Would be nice to avoid any layout shift on page load, like we have with the current UI. It's nasty since it moves all the page content.

https://github.com/ProfessionalWiki/PageApprovals/assets/146040/9a57eb62-330f-4571-9d5a-8bd1f558a4c6

Perhaps we can inline some CSS, so we don't wait on the resource loader module loading.

**Comment by malberts** [comment]
> Perhaps we can inline some CSS, so we don't wait on the resource loader module loading.

IIRC the trick here is to define two separate ResourceLoaderModules and load the CSS and JS separately:

```php
$this->out->addModuleStyles( 'ext.pageApprovals.styles' );
$this->out->addModules( 'ext.pageApprovals' );
```

The first method loads the CSS with a `<link>` tag, whereas the second one loads the CSS/JS via the JS ResourceLoader, which is slower.

**Comment by waximabbax** [comment]
WIP

![image](https://github.com/ProfessionalWiki/PageApprovals/assets/15813104/95e90d51-498a-4882-922b-8c7cafa10f04)


Trying my best to use minimal icons without libraries.

**Comment by JeroenDeDauw** [comment]
Looks nice. Main concern I have is that the reject button is way too attention grabbing. It's the most visible thing on the page. The way it is done in the video I linked before (https://chat.professional.wiki/pro-wiki/channels/bayer-tech/5ajgr4tfhby35mzihaqnd9mkar) is to not have this button on the page at all. There the user has to click on the current status to change it. Would that be doable without a lot of work? I should ask the client what they want, but ideally I can send them a reasonable guess from our side first.
