### ISSUE TITLE
Add approval details to UI

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#46]
When approved, show a message like: 
> John Doe approved this page on 2024-04-22

Data is already available in `OutputPageUiPresenter`

This follows-up to
* https://github.com/ProfessionalWiki/PageApprovals/issues/2

Related
* https://github.com/ProfessionalWiki/PageApprovals/issues/46

**Comment by waximabbax** [comment]
Should Approval Details be visible to the public?

**Comment by JeroenDeDauw** [comment]
Yes. When looking at a page as any user, I should see the approval state, which includes approved/unnaproved, but also the when and who.

**Comment by malberts** [comment]
This would presumably also be updated when the API action succeeds. PR to add some Approval state details to the API response: https://github.com/ProfessionalWiki/PageApprovals/pull/62

**Comment by JeroenDeDauw** [comment]
Is this done?
