### ISSUE TITLE
Detect content changes

### ISSUE THREAD

**Issue by JeroenDeDauw** [ProfessionalWiki/PageApprovals#6]
On approval, save page HTML (see https://github.com/ProfessionalWiki/PageApprovals/issues/5)

On page render, compare saved HTML with current HTML, and save approval state of page somewhere (so it can be queried by pending approval pages https://github.com/ProfessionalWiki/PageApprovals/issues/7)

Complication: render might not happen if no one looks at the page. This is an issue for [the task list ](https://github.com/ProfessionalWiki/PageApprovals/issues/7)

**Comment by malberts** [comment]
This hook might be useful to detect when the parser cache itself is updated: https://www.mediawiki.org/wiki/Manual:Hooks/ParserCacheSaveComplete

**Comment by JeroenDeDauw** [comment]
https://www.mediawiki.org/wiki/Manual:Hooks/OutputPageParserOutput seems like the way to go. I verified it is only called on parse and not on every page display.
