### ISSUE TITLE
Cannot add multiple categories

### ISSUE THREAD

**Issue by malberts** [ProfessionalWiki/PageApprovals#93]
This is happening on a production wiki.

https://github.com/user-attachments/assets/f14956e4-78c4-41ab-bb7b-091dacbc86f6

**Comment by malberts** [comment]
This is also not working locally. But more specifically, it looks like it does not work when there are multiple users:
[Screencast_20240806_111229.webm](https://github.com/user-attachments/assets/ac84f61a-6de0-49cb-b9eb-b6fefd537340)

**Comment by malberts** [comment]
This is also not working locally. More specifically, I cannot add multiple categories for more users when there are multiple users.

https://github.com/user-attachments/assets/a64b34e9-a898-4bf2-a361-52f1f061643b

**Comment by JeroenDeDauw** [comment]
weird bug. I just added 2nd category to my user on production, but indeed, I cannot add a second one to the other users. 
![image](https://github.com/user-attachments/assets/ba7d932c-9ee3-4297-a2db-acb8038b50f4)
